{% set version = '0.5.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-graphtweets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/graphTweets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/graphTweets/graphTweets_{{ version }}.tar.gz
  sha256: 07f8f435150ec5185e6144e3ddf993062e4340ff763a23dbf20f6f4e1915c549

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-combinat
    - r-dplyr
    - r-igraph
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tidyr
    - r-zeallot
  run:
    - r-base
    - r-combinat
    - r-dplyr
    - r-igraph
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tidyr
    - r-zeallot

test:
  commands:
    - $R -e "library('graphTweets')"           # [not win]
    - "\"%R%\" -e \"library('graphTweets')\""  # [win]

about:
  home: http://graphTweets.john-coene.com
  license: MIT
  summary: Allows building an edge table from data frame of tweets, also provides function to
    build nodes and another create a temporal graph.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: graphTweets
# Type: Package
# Title: Visualise Twitter Interactions
# Version: 0.5.3
# Date: 2020-01-02
# Authors@R: person("John", "Coene", email = "jcoenep@gmail.com", role = c("aut", "cre"))
# Description: Allows building an edge table from data frame of tweets, also provides function to build nodes and another create a temporal graph.
# License: MIT + file LICENSE
# Depends: R (>= 3.2.0)
# Imports: dplyr, igraph, purrr, rlang, magrittr, utils, tidyr, zeallot, combinat
# RoxygenNote: 7.0.2
# URL: http://graphTweets.john-coene.com
# BugReports: https://github.com/JohnCoene/graphTweets/issues
# Suggests: rtweet, testthat
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2020-01-07 12:45:28 UTC; jcoe
# Author: John Coene [aut, cre]
# Maintainer: John Coene <jcoenep@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-01-08 09:00:08 UTC
