travis:
  secure:
    BINSTAR_TOKEN: DxV6S6aGu3VYm/pDUV8g7qRvdUG7Cn61AhASEhHBvPJ3wn+vhSYHIWdNED/7/p/qhjvj1jmKI+0D5k1xIs+FRAqpSGjZ+KUsy7eJTzNAdALWe0IXjQtgQCiczbqM7OKF4NfSwudWouXuAvr12RKTcQaaIT+HKMKMrLpQMSvzPFWyWIB+vvXQFb5LtJH1rKAVW9qI7QXVC2hdncqUJSMZDgDfAEftN7VWOqWmgaEF7zDMeC8DNncvfOiZVMWHvS7hNBsA/JMq12yt6JbWthgKCXdMW5HUt+gBsGKVZQGT8RbfQUrR/zU49KWVzmOFc1H8GHA9HcdychxOoyYeeibfnnOA9lgs8do5DSM/4WMiuGujwoYpS+o7eLkpA0tTaZncm+HuDJ5qMq6D31chsQCR9QKjpcSGpZe57zQEjgMPLgModAL4wwZJAGcp3Fv7hC1hUb/GHNhydOp/982kwKdyuTbTQmbJ2cWe6H5ZMG3aQLBKu8PxZ+zxe266sVFRdaBZei6Bjgy9+43yN+5jEZUPM/Q+q0ljNMcM2pGbl6xNAOcKGYoOSWs4lgGIRwHQxakXarSnn4AvWQCEOljK1QSbVfdaWDDcnwe8Nt75vQXAADCJwV6po+APuHNume8gvdH4g0YnUf3aUW4J7cKebLQ0HS6recG9nhg6Mm+3z8ywKtM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
